const review=await fetch('rov_results.json').then(r=>{if(!r.ok)throw Error('ROV 결과를 불러올 수 없습니다.');return r.json();});
const records=review.records;
let currentDamage=-1;
function visibleIndices(){const kind=document.getElementById('class-filter').value,frame=document.getElementById('frame-filter').value,group=document.getElementById('group-filter').value;return records.map((r,i)=>i).filter(i=>(kind==='all'||records[i].kind===kind)&&(frame==='all'||records[i].image===frame)&&(group==='all'||records[i].frame_group===group));}
const markerVertex=`#version 300 es
layout(location=0)in vec3 position;layout(location=1)in vec3 color;layout(location=2)in vec3 pickColor;layout(location=3)in float recordId;
uniform mat4 vp;uniform float selectedId;uniform float pointScale;out vec3 rgb;out vec3 pick;
void main(){gl_Position=vp*vec4(position,1.0);gl_PointSize=(abs(recordId-selectedId)<0.1?23.0:14.0)*pointScale;rgb=abs(recordId-selectedId)<0.1?vec3(1.0):color;pick=pickColor;}`;
const markerFragment=`#version 300 es
precision highp float;in vec3 rgb;in vec3 pick;uniform bool picking;out vec4 pixel;
void main(){float d=length(gl_PointCoord-vec2(0.5));if(d>0.5)discard;pixel=vec4(picking?pick:(d>0.37?vec3(0.04,0.08,0.12):rgb),1.0);}`;
const markerProgram=gl.createProgram();gl.attachShader(markerProgram,shader(gl.VERTEX_SHADER,markerVertex));gl.attachShader(markerProgram,shader(gl.FRAGMENT_SHADER,markerFragment));gl.linkProgram(markerProgram);
if(!gl.getProgramParameter(markerProgram,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(markerProgram));
const markerLoc=Object.fromEntries(['vp','selectedId','pointScale','picking'].map(k=>[k,gl.getUniformLocation(markerProgram,k)]));
const markerValues=[];
records.forEach((r,i)=>{const id=draws.length+i+1,color=r.kind==='CRC'?[1,0.16,0.19]:[1,0.89,0.1];markerValues.push(...r.gltf_xyz.map((v,k)=>v-center[k]),...color,(id&255)/255,((id>>8)&255)/255,((id>>16)&255)/255,i);});
const markerVao=gl.createVertexArray();gl.bindVertexArray(markerVao);const markerBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,markerBuffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(markerValues),gl.STATIC_DRAW);
for(const [index,size,offset]of[[0,3,0],[1,3,12],[2,3,24],[3,1,36]]){gl.enableVertexAttribArray(index);gl.vertexAttribPointer(index,size,gl.FLOAT,false,40,offset);}
function drawMarkers(vp,picking){gl.useProgram(markerProgram);gl.uniformMatrix4fv(markerLoc.vp,false,new Float32Array(vp));gl.uniform1f(markerLoc.selectedId,currentDamage);gl.uniform1f(markerLoc.pointScale,Math.min(devicePixelRatio||1,2));gl.uniform1i(markerLoc.picking,picking?1:0);if(document.getElementById('xray').checked)gl.disable(gl.DEPTH_TEST);else{gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);}gl.bindVertexArray(markerVao);const visible=visibleIndices();for(const i of visible)if(i!==currentDamage)gl.drawArrays(gl.POINTS,i,1);if(visible.includes(currentDamage))gl.drawArrays(gl.POINTS,currentDamage,1);gl.depthFunc(gl.LESS);}
const dom=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
function renderList(){const list=document.getElementById('location-list');list.replaceChildren();const indices=visibleIndices();document.getElementById('visible-count').textContent=indices.length+'건';for(const i of indices){const r=records[i],button=dom('button',undefined,'location-row '+(r.kind==='CRC'?'crack-row':'spall-row'));button.dataset.damage=r.id;button.setAttribute('aria-pressed',String(i===currentDamage));button.append(dom('strong',r.id+' · '+r.name),dom('small',r.image+' · '+r.frame_group+' ('+(r.frame_group_index+1)+'/'+r.frame_group_size+')'));button.onclick=()=>selectDamage(i,true);list.append(button);}if(!indices.length)list.append(dom('p','조건에 맞는 손상이 없습니다.','empty-state'));document.getElementById('prev').disabled=document.getElementById('next').disabled=!indices.length;}
function imageBlock(title,path,r,outline=false){const box=dom('div'),heading=dom('div',undefined,'image-heading');heading.append(dom('span',title));const link=dom('a','크게 보기');link.href=path;link.target='_blank';link.rel='noopener';heading.append(link);const wrapper=dom('div',undefined,'image-wrapper'),image=dom('img',undefined,'review-image');image.src=path;image.alt=r.id+' '+title;wrapper.append(image);if(outline){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox',`0 0 ${r.image_width} ${r.image_height}`);svg.setAttribute('aria-hidden','true');const p=document.createElementNS(svg.namespaceURI,'polygon');p.setAttribute('points',r.nodes.map(n=>n.join(',')).join(' '));p.setAttribute('fill',r.kind==='CRC'?'#ff333350':'#ffe22c50');p.setAttribute('stroke',r.kind==='CRC'?'#ff4545':'#ffe22c');p.setAttribute('stroke-width','3');svg.append(p);wrapper.append(svg);}box.append(heading,wrapper);return box;}
function selectDamage(i,focus=true){if(!records[i])return;currentDamage=i;const r=records[i];selected=draws.findIndex(d=>d.nodeId===r.node_id);const detail=document.getElementById('location-detail');detail.replaceChildren(dom('h2',r.id+' · '+r.name),dom('div','시연용 랜덤 3D 위치','status-tag'));const fields=dom('dl',undefined,'fields');const add=(label,value)=>fields.append(dom('dt',label),dom('dd',value));add('프레임',r.image);add('유사 프레임 묶음',r.frame_group+' · '+(r.frame_group_index+1)+' / '+r.frame_group_size+'장');add('가로 이동',r.frame_offset_x_m.toFixed(2)+' m · 묶음 첫 프레임 기준');add('부재',r.member);add('부재 ID',r.member_id);add('구획',r.section);add('격자',r.grid||'격자 없음 · 부재 연결');add('배치 행',r.grid_band==='lower'?'바로 아래 격자':'수면 인접 격자');add('대표 XYZ',r.world_xyz.map(v=>v.toFixed(3)).join(' / ')+' m');add('모델 수면',r.water_level.toFixed(3)+' m');add('수면 아래',r.submergence.toFixed(2)+' m · 시연 깊이');add('예측 면적',r.area_px.toLocaleString()+' px');add('모델 신뢰도',(100*r.confidence).toFixed(2)+'%');detail.append(fields,imageBlock('원본 프레임 · 선택 영역 윤곽',r.raw_preview,r,true),imageBlock('손상 Overlay · 정사각형 Crop',r.overlay_preview,r));document.getElementById('selection').textContent=r.id+' · '+r.name+' · '+r.image;if(focus){target=r.gltf_xyz.map((v,k)=>v-center[k]);distance=8;const n=r.normal_gltf;azimuth=Math.atan2(n[0],n[2]);elevation=Math.max(-.65,Math.min(.65,Math.asin(n[1])))+.12;}renderList();draw();updateStatus();const q=new URLSearchParams(location.search);q.delete('token');q.set('damage',r.id);history.replaceState(null,'','?'+q);window.ROV_VIEWER_STATS.selected=r.id;}
function fitDamage(){const indices=visibleIndices();if(!indices.length)return;const low=[0,1,2].map(k=>Math.min(...indices.map(i=>records[i].gltf_xyz[k]))),high=[0,1,2].map(k=>Math.max(...indices.map(i=>records[i].gltf_xyz[k])));target=low.map((v,k)=>(v+high[k])/2-center[k]);distance=Math.max(6,Math.hypot(...low.map((v,k)=>high[k]-v))*1.5);azimuth=Math.PI*.43;elevation=Math.PI*.12;draw();}
function changeFilter(){renderList();const indices=visibleIndices();if(indices.length&&!indices.includes(currentDamage))selectDamage(indices[0],false);draw();updateStatus();window.ROV_VIEWER_STATS.visible=indices.length;}
for(const name of [...new Set(records.map(r=>r.image))].sort()){const o=dom('option',name);o.value=name;document.getElementById('frame-filter').append(o);}
for(const group of [...new Set(records.map(r=>r.frame_group))].sort()){const size=records.find(r=>r.frame_group===group).frame_group_size;const o=dom('option',group+' · '+size+'장'+(size>1?' · 유사 프레임':''));o.value=group;document.getElementById('group-filter').append(o);}
document.getElementById('class-filter').onchange=changeFilter;document.getElementById('frame-filter').onchange=changeFilter;document.getElementById('group-filter').onchange=()=>{changeFilter();fitDamage();};
document.getElementById('damage-fit').onclick=fitDamage;document.getElementById('focus').onclick=()=>selectDamage(currentDamage,true);
for(const [id,step]of[['prev',-1],['next',1]])document.getElementById(id).onclick=()=>{const list=visibleIndices(),j=list.indexOf(currentDamage);if(list.length)selectDamage(list[(j+step+list.length)%list.length],true);};
for(const id of ['xray','layer','water'])document.getElementById(id).onchange=()=>draw();
window.ROV_VIEWER_STATS={...review.summary,marker_count:records.length,visible:records.length,selected:null};
window.ROV_VIEWER_API={select:id=>{const i=records.findIndex(r=>r.id===id);if(i<0)throw Error('알 수 없는 손상');selectDamage(i,true);},fit:fitDamage,visible:()=>visibleIndices().map(i=>records[i].id)};
renderList();
