'use strict';
(async function(){
 const status=document.getElementById('status'), canvas=document.getElementById('canvas');
 try {
 const payload=JSON.parse(document.getElementById('model-data').textContent), model=payload.gltf;
 const gl=canvas.getContext('webgl2',{antialias:true,preserveDrawingBuffer:true});
 if(!gl)throw Error('WebGL2를 사용할 수 없습니다. WebGL2를 지원하는 브라우저에서 이 파일을 열어 주세요.');
 const decode=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
 const buffers=payload.buffers.map(s=>decode(s).buffer);
 const widths={SCALAR:1,VEC2:2,VEC3:3,VEC4:4,MAT4:16};
 const sizes={5120:1,5121:1,5122:2,5123:2,5125:4,5126:4};
 function acc(id){const a=model.accessors[id],v=model.bufferViews[a.bufferView],n=widths[a.type],size=sizes[a.componentType],stride=v.byteStride||n*size,offset=(v.byteOffset||0)+(a.byteOffset||0),dv=new DataView(buffers[v.buffer]);const out=new Float64Array(a.count*n);for(let i=0;i<a.count;i++)for(let j=0;j<n;j++){const q=offset+i*stride+j*size;let x;switch(a.componentType){case 5126:x=dv.getFloat32(q,true);break;case 5125:x=dv.getUint32(q,true);break;case 5123:x=dv.getUint16(q,true);break;case 5122:x=dv.getInt16(q,true);break;case 5121:x=dv.getUint8(q);break;default:x=dv.getInt8(q);}if(a.normalized&&a.componentType!==5126)x=a.componentType===5121?x/255:a.componentType===5123?x/65535:a.componentType===5120?Math.max(-1,x/127):Math.max(-1,x/32767);out[i*n+j]=x;}return out;}
 const identity=()=>[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];
 function multiply(a,b){const c=new Array(16).fill(0);for(let j=0;j<4;j++)for(let i=0;i<4;i++)for(let k=0;k<4;k++)c[j*4+i]+=a[k*4+i]*b[j*4+k];return c;}
 function local(n){if(n.matrix)return n.matrix;const t=n.translation||[0,0,0],s=n.scale||[1,1,1],q=n.rotation||[0,0,0,1],[x,y,z,w]=q;return[(1-2*y*y-2*z*z)*s[0],(2*x*y+2*w*z)*s[0],(2*x*z-2*w*y)*s[0],0,(2*x*y-2*w*z)*s[1],(1-2*x*x-2*z*z)*s[1],(2*y*z+2*w*x)*s[1],0,(2*x*z+2*w*y)*s[2],(2*y*z-2*w*x)*s[2],(1-2*x*x-2*y*y)*s[2],0,t[0],t[1],t[2],1];}
 const draws=[], min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];
 function walk(id,parent){const n=model.nodes[id],world=multiply(parent,local(n));if(n.mesh!==undefined){const mesh=model.meshes[n.mesh];for(const primitive of mesh.primitives){const p=acc(primitive.attributes.POSITION),normal=acc(primitive.attributes.NORMAL),uv=primitive.attributes.TEXCOORD_0===undefined?new Float64Array(p.length/3*2):acc(primitive.attributes.TEXCOORD_0),positions=new Float64Array(p.length),normals=new Float32Array(normal.length);for(let i=0;i<p.length;i+=3){for(let k=0;k<3;k++){positions[i+k]=world[k]*p[i]+world[4+k]*p[i+1]+world[8+k]*p[i+2]+world[12+k];min[k]=Math.min(min[k],positions[i+k]);max[k]=Math.max(max[k],positions[i+k]);normals[i+k]=world[k]*normal[i]+world[4+k]*normal[i+1]+world[8+k]*normal[i+2];}}const ix=primitive.indices===undefined?Float64Array.from({length:p.length/3},(_,i)=>i):acc(primitive.indices),indices=Uint32Array.from(ix),name=n.name||mesh.name||`시설 ${id}`;draws.push({name,node:n,nodeId:id,meshId:n.mesh,material:primitive.material,positions,normals,uv:new Float32Array(uv),indices,region:/^(SPW|NOF_R|NOF_L)_\d+/.test(name),terrain:/지형|수면/.test(name)||(/^SPW_\d+/.test(name)&&n.extras?.face===1)});}}for(const child of n.children||[])walk(child,world);}
 for(const id of model.scenes[model.scene||0].nodes)walk(id,identity());
 const center=min.map((x,k)=>(x+max[k])/2),extent=min.map((x,k)=>max[k]-x),radius=Math.hypot(...extent)/2;
 let triangles=0;for(const d of draws){for(let i=0;i<d.positions.length;i++)d.positions[i]-=center[i%3];triangles+=d.indices.length/3;}
 function shader(type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;}
 const vertex=`#version 300 es
 layout(location=0)in vec3 p;layout(location=1)in vec3 n;layout(location=2)in vec2 uv;uniform mat4 vp;out vec2 texcoord;out vec3 normal;void main(){gl_Position=vp*vec4(p,1.0);texcoord=uv;normal=normalize(n);}`;
 const fragment=`#version 300 es
 precision highp float;in vec2 texcoord;in vec3 normal;uniform sampler2D image;uniform vec4 color;uniform int mode;uniform vec3 pick;uniform bool selected;out vec4 pixel;void main(){if(mode==2){pixel=vec4(pick,1.0);return;}vec3 rgb=mode==0?texture(image,texcoord).rgb*color.rgb:color.rgb*(0.70+0.30*abs(dot(normalize(normal),normalize(vec3(0.4,0.8,0.5)))));if(selected)rgb=mix(rgb,vec3(1.0,0.88,0.25),0.55);pixel=vec4(rgb,1.0);}`;
 const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,vertex));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,fragment));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));gl.useProgram(program);
 const loc=Object.fromEntries(['vp','image','color','mode','pick','selected'].map(k=>[k,gl.getUniformLocation(program,k)]));
 function attr(data,index,size){const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,data,gl.STATIC_DRAW);gl.enableVertexAttribArray(index);gl.vertexAttribPointer(index,size,gl.FLOAT,false,0,0);}
 for(const d of draws){d.vao=gl.createVertexArray();gl.bindVertexArray(d.vao);attr(new Float32Array(d.positions),0,3);attr(d.normals,1,3);attr(d.uv,2,2);const ib=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ib);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,d.indices,gl.STATIC_DRAW);}
 const textures=await Promise.all(payload.images.map(uri=>new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>{const t=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,t);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,false);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,image);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.REPEAT);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.REPEAT);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR_MIPMAP_LINEAR);gl.generateMipmap(gl.TEXTURE_2D);resolve(t);};image.onerror=reject;image.src=uri;})));
 const minus=(a,b)=>a.map((x,k)=>x-b[k]),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],unit=a=>{const n=Math.hypot(...a);return a.map(x=>x/n);},dot=(a,b)=>a.reduce((s,x,k)=>s+x*b[k],0);
 function view(eye,target){const z=unit(minus(eye,target)),x=unit(cross([0,1,0],z)),y=cross(z,x);return[x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,eye),-dot(y,eye),-dot(z,eye),1];}
 function perspective(aspect){const f=1/Math.tan(Math.PI/8),near=Math.max(radius/2000,0.005),far=radius*150;return[f/aspect,0,0,0,0,f,0,0,0,0,(far+near)/(near-far),-1,0,0,2*far*near/(near-far),0];}
 function regionColor(d){let base=d.name.startsWith('SPW')?(d.node.extras?.face===1?[0.20,0.42,0.88]:[0.24,0.70,0.96]):d.name.startsWith('NOF_R')?[0.90,0.45,0.76]:[1.0,0.73,0.30];const n=Number(d.name.split('_').at(-1)),v=0.64+0.36*((n*0.61803398875)%1);return[...base.map(x=>x*v),1];}
 let azimuth=-Math.PI*0.38,elevation=Math.PI*0.22,distance=radius*2.5,target=[0,0,0],selected=-1,drag=null,pickFramebuffer=null,pickColor=null,pickDepth=null,lastSize='';
 function resize(){const ratio=Math.min(window.devicePixelRatio||1,2),w=Math.round(canvas.clientWidth*ratio),h=Math.round(canvas.clientHeight*ratio);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}const key=w+':'+h;if(lastSize===key)return;lastSize=key;if(pickFramebuffer){gl.deleteFramebuffer(pickFramebuffer);gl.deleteTexture(pickColor);gl.deleteRenderbuffer(pickDepth);}pickFramebuffer=gl.createFramebuffer();pickColor=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,pickColor);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA8,w,h,0,gl.RGBA,gl.UNSIGNED_BYTE,null);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);pickDepth=gl.createRenderbuffer();gl.bindRenderbuffer(gl.RENDERBUFFER,pickDepth);gl.renderbufferStorage(gl.RENDERBUFFER,gl.DEPTH_COMPONENT24,w,h);gl.bindFramebuffer(gl.FRAMEBUFFER,pickFramebuffer);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,pickColor,0);gl.framebufferRenderbuffer(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,gl.RENDERBUFFER,pickDepth);gl.bindFramebuffer(gl.FRAMEBUFFER,null);}
 function draw(picking=false){resize();gl.bindFramebuffer(gl.FRAMEBUFFER,picking?pickFramebuffer:null);gl.viewport(0,0,canvas.width,canvas.height);gl.clearColor(...(picking?[0,0,0,1]:[0.10,0.16,0.23,1]));gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.disable(gl.BLEND);gl.disable(gl.CULL_FACE);if(picking)gl.disable(gl.DITHER);else gl.enable(gl.DITHER);const eye=[target[0]+distance*Math.cos(elevation)*Math.sin(azimuth),target[1]+distance*Math.sin(elevation),target[2]+distance*Math.cos(elevation)*Math.cos(azimuth)],vp=multiply(perspective(canvas.width/canvas.height),view(eye,target));gl.useProgram(program);gl.uniformMatrix4fv(loc.vp,false,new Float32Array(vp));gl.uniform1i(loc.image,0);const colorMode=document.getElementById('mode').value==='regions';for(let i=0;i<draws.length;i++){const d=draws[i];if(d.terrain&&!document.getElementById('land').checked)continue;const mat=model.materials[d.material],pbr=mat.pbrMetallicRoughness||{},t=pbr.baseColorTexture;gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,textures[model.textures[t.index].source]);gl.uniform1i(loc.mode,picking?2:colorMode?1:0);gl.uniform4fv(loc.color,colorMode?(d.region?regionColor(d):[0.44,0.50,0.57,1]):pbr.baseColorFactor||[1,1,1,1]);const id=i+1;gl.uniform3f(loc.pick,(id&255)/255,((id>>8)&255)/255,((id>>16)&255)/255);gl.uniform1i(loc.selected,i===selected?1:0);gl.bindVertexArray(d.vao);gl.drawElements(gl.TRIANGLES,d.indices.length,gl.UNSIGNED_INT,0);}gl.bindFramebuffer(gl.FRAMEBUFFER,null);}
 function updateStatus(){status.textContent=`${draws.length.toLocaleString()} meshes · ${triangles.toLocaleString()} 삼각형 · 18개 512px 텍스처 · 중심 제거: (${center.map(x=>x.toFixed(2)).join(', ')}) · 범위 XYZ: ${extent.map(x=>x.toFixed(1)).join(' × ')} (모델 좌표 단위)`;}
 canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,move:0,pan:e.button===2||e.shiftKey};});canvas.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.move+=Math.abs(dx)+Math.abs(dy);drag.x=e.clientX;drag.y=e.clientY;if(drag.pan){const s=distance/canvas.clientHeight*0.8;target[0]-=dx*s*Math.cos(azimuth);target[2]+=dx*s*Math.sin(azimuth);target[1]+=dy*s;}else{azimuth-=dx*0.006;elevation=Math.max(-Math.PI/2+0.01,Math.min(Math.PI/2-0.01,elevation+dy*0.006));}draw();});canvas.addEventListener('pointerup',e=>{if(!drag)return;const click=drag.move<5&&!drag.pan;drag=null;if(click){draw(true);gl.bindFramebuffer(gl.FRAMEBUFFER,pickFramebuffer);const r=canvas.getBoundingClientRect(),p=new Uint8Array(4),x=Math.floor((e.clientX-r.left)*canvas.width/r.width),y=canvas.height-1-Math.floor((e.clientY-r.top)*canvas.height/r.height);gl.readPixels(x,y,1,1,gl.RGBA,gl.UNSIGNED_BYTE,p);selected=p[0]+p[1]*256+p[2]*65536-1;gl.bindFramebuffer(gl.FRAMEBUFFER,null);const d=draws[selected];document.getElementById('selection').textContent=d?`${d.name}${d.region?` · face ${d.node.extras?.face} · row ${d.node.extras?.row} / col ${d.node.extras?.col} · 記録面積 ${d.node.extras?.area} (モデル単位²)`:''} · mesh ${d.meshId}`:'選択なし';draw();}});canvas.addEventListener('pointercancel',()=>drag=null);canvas.addEventListener('wheel',e=>{e.preventDefault();distance=Math.max(radius*0.03,Math.min(radius*25,distance*Math.exp(e.deltaY*0.001)));draw();},{passive:false});
 document.getElementById('fit').onclick=()=>{target=[0,0,0];distance=radius*2.5;azimuth=-Math.PI*0.38;elevation=Math.PI*0.22;draw();};document.getElementById('front').onclick=()=>{target=[0,0,0];distance=radius*2.2;azimuth=Math.PI*0.43;elevation=Math.PI*0.14;draw();};document.getElementById('top').onclick=()=>{target=[0,0,0];distance=radius*2.4;elevation=Math.PI/2-0.01;draw();};document.getElementById('save').onclick=()=>{draw();const a=document.createElement('a');a.download='daecheongdam_preview.png';a.href=canvas.toDataURL('image/png');a.click();};document.getElementById('mode').onchange=()=>draw();document.getElementById('land').onchange=()=>draw();window.addEventListener('resize',()=>draw());draw();updateStatus();window.MODEL_PREVIEW_READY=true;window.MODEL_PREVIEW_STATS={meshCount:draws.length,triangleCount:triangles,center,extent};
 }catch(e){document.getElementById('error').style.display='block';document.getElementById('error').textContent=String(e)+'\n'+String(e.stack||'');status.textContent='表示できませんでした。上のエラーを確認してください。';window.MODEL_PREVIEW_ERROR=String(e);}
})();
